### ISSUE TITLE
Text boxes cut off

### ISSUE THREAD

**Issue by UnionExxis** [VitorVilela7/wide-snes#38] opened 2022-01-13 02:43 UTC
Hello, I'm using v1.10 for 16:9 raw ("smw-widescreen-raw-v110.bso) on Retroarch 1.9.11 with the latest BSNES HD Beta Core (version 10.6). 

I get this issue where the text boxes in the game aren't showing the whole text. Oddly, I do not get the issue when using the 16:9 "par" .bso.
![smw-widescreen-raw-v110-220112-212836](https://user-images.githubusercontent.com/73078011/149256412-b26c86f4-00e7-4774-bda2-9c3308279758.png)

I can't figure out if this is an emulator setting issue or what because the settings for BSNES HD Beta are the same between the v110 raw and v110 par.

Any hints or tips on how to resolve this would be appreciated.

**Comment by VitorVilela7** [comment] 2022-07-02 19:42
Hi, are you still having issues with this? I heard similar issues which apparently it's caused by the missing "S2" on 'smw-widescreen-raw-v110.bso'

**Comment by UnionExxis** [comment] 2022-07-02 21:48
@VitorVilela7 No, I think it was actually an emulator setting in Retroarch BSNES HD that was causing it. Unfortunately, it's been long enough that I forgot which setting fixed it.

**Comment by VitorVilela7** [comment] 2022-07-02 22:04
I see, thanks for the quick response @UnionExxis, I will close the issue since it was an emulator setting.

**Closed by VitorVilela7** 2022-07-02 22:04 UTC
Labels: bug
