### ISSUE TITLE
bad scalling of black iris in opening and endings

### ISSUE THREAD

**Issue by DigiDwrf** [VitorVilela7/wide-snes#20] opened 2021-06-22 02:36 UTC
![Screenshot_20210621_213150_com retroarch aarch64](https://user-images.githubusercontent.com/74699493/122853961-a51f6880-d2d8-11eb-8b6d-2fa86a289403.jpg)

I'm using Retroarch emulator. Can you help me? Thank you.

**Comment by VitorVilela7** [comment] 2021-06-22 03:00
When this happens it means that it didn't load the BSO file.

1) Is the BSO file on the same folder as the ROM (SMC or SFC) file? It must stay in the same folder to work.
2) Does the BSO file has the same name as the ROM (SMC or SFC) file? It must have the same name as the ROM to work.
3) Are you using the latest bsnes_hd core? Latest version is beta 06

**Comment by VitorVilela7** [comment] 2021-06-22 03:05
Duplicate of #17

**Comment by VitorVilela7** [comment] 2023-01-08 15:44
I believe the most recent documentation and release instructions should make it more clear how to set up widescreen SMW. Please let me know if you still have issues.

**Closed by VitorVilela7** 2023-01-08 15:44 UTC
Labels: configuration issue

**Comment by DigiDwrf** [comment] 2023-01-08 20:16
Hey! Sure, I could fix it a lot ago, thank you very much!
